apiVersion: v1
kind: Service
metadata:
  name: app-name
  labels:
    app: app-name
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: health
    port: 8081
    targetPort: health
    protocol: TCP
  selector:
    app: app-name
